# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: monk_pasture-蒙牛有机牧场

on:
  workflow_dispatch:
  schedule:
    - cron: '*/40 * * * *'
  repository_dispatch:
    types: 蒙牛有机牧场
jobs:
  build:

    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: tubie75/jdqd
          ref: main
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache node_modules
        uses: actions/cache@v2 # 使用 GitHub 官方的缓存 Action。
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('package-lock.json') }} # 使用 package-lock.json 的 Hash 作为缓存的 key。也可以使用 package.json 代替
      - name: npm install
        run: |
          npm install
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: '等待'
        run: |
             python3 wait.py 23:59:59.990
      - name: '蒙牛有机牧场'
        run: |
          node monk_pasture.js
          
        env:
          JD_COOKIE: ${{ secrets.JD_COOKIE }}
          JD_USER_AGENT: ${{ secrets.JD_USER_AGENT }}
          JD_DEBUG: ${{ secrets.JD_DEBUG }}
          PASTURE_EXCHANGE_KEYWORD: ${{ '1京豆' }}
          PASTURE_AUTOLEVELUP: ${{ false }}
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
          PURCHASE_SHOPS: ${{ secrets.PURCHASE_SHOPS }}


