# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: jd_shop_sign-店铺签到

on:
  workflow_dispatch:
  schedule:
    - cron: '10 16,4 * * *'
  repository_dispatch:
    types: 店铺签到
jobs:
  build:

    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: tubie75/jdqd
          ref: main
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache node_modules
        uses: actions/cache@v2 # 使用 GitHub 官方的缓存 Action。
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('package-lock.json') }} # 使用 package-lock.json 的 Hash 作为缓存的 key。也可以使用 package.json 代替
      - name: npm install
        run: |
          npm install
      - name: '店铺签到'
        run: |
          node jd_shop_sign.js
          curl https://raw.githubusercontent.com/wulove/my_scripts/master/jd_dpqd.js -o jd_dpqd.js
          node jd_dpqd.js
          curl https://raw.githubusercontent.com/hajiuhajiu/jdsign1112/master/jd_dpqd.js -o jd_dpqd_1.js
          node jd_dpqd_1.js
        env:
          JD_COOKIE: ${{ secrets.JD_COOKIE }}
          JD_USER_AGENT: ${{ secrets.JD_USER_AGENT }}
          JD_DEBUG: ${{ secrets.JD_DEBUG }}
          #PUSH_KEY: ${{ secrets.PUSH_KEY }}
